### ISSUE TITLE
Needs to be updated?

### ISSUE THREAD

**Issue by namelivia** [beoran/chipmunk#18]
Hi, I made a game a couple of years ago using this gem. But now on my new system I have not being able to run it. The requires are the same I had before, I have installed the chipmunk gem but the console still says:

"uninitialized constant CP::Vec2::ZERO (NameError)"

I guess it's a versioning issue, maybe the gem needs to be updated. I'm using ruby 2.1.3p242.
What confuses me is that I have  a .gem/ruby/2.1.0/gems/chipmunk-6.1.3.1/ folder.
Is it compatible? If is easy to update or fix I can try to do it myself.

**Comment by shawn42** [comment]
I haven't forgotten about this. I just ripped out the rake-compiler, precompiling on windows parts of the build and simplified the gem to be just a straight c-ext gem. If anyone would like to maintain a build system for multiple windows versions, multiple ruby versions, and 32/64bit, please contact me or just fork this gem. Right now, native window gem building is holding up releases. For now, users will just need to install DevKit on windows.
